/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface TextTag {
    'className': string;
    'textStyle': { [key: string]: string };
    'wrap': boolean;
  }
  interface TextTagAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'textStyle'?: { [key: string]: string };
    'wrap'?: boolean;
  }

  interface DefaultButton {
    'className': string;
  }
  interface DefaultButtonAttributes extends StencilHTMLAttributes {
    'className'?: string;
  }

  interface ArrowIcon {
    'color': string;
    'height': number;
    'viewBox': string;
    'width': number;
  }
  interface ArrowIconAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'height'?: number;
    'viewBox'?: string;
    'width'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'TextTag': Components.TextTag;
    'DefaultButton': Components.DefaultButton;
    'ArrowIcon': Components.ArrowIcon;
  }

  interface StencilIntrinsicElements {
    'text-tag': Components.TextTagAttributes;
    'default-button': Components.DefaultButtonAttributes;
    'arrow-icon': Components.ArrowIconAttributes;
  }


  interface HTMLTextTagElement extends Components.TextTag, HTMLStencilElement {}
  var HTMLTextTagElement: {
    prototype: HTMLTextTagElement;
    new (): HTMLTextTagElement;
  };

  interface HTMLDefaultButtonElement extends Components.DefaultButton, HTMLStencilElement {}
  var HTMLDefaultButtonElement: {
    prototype: HTMLDefaultButtonElement;
    new (): HTMLDefaultButtonElement;
  };

  interface HTMLArrowIconElement extends Components.ArrowIcon, HTMLStencilElement {}
  var HTMLArrowIconElement: {
    prototype: HTMLArrowIconElement;
    new (): HTMLArrowIconElement;
  };

  interface HTMLElementTagNameMap {
    'text-tag': HTMLTextTagElement
    'default-button': HTMLDefaultButtonElement
    'arrow-icon': HTMLArrowIconElement
  }

  interface ElementTagNameMap {
    'text-tag': HTMLTextTagElement;
    'default-button': HTMLDefaultButtonElement;
    'arrow-icon': HTMLArrowIconElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
