/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ArrowIcon {
    'color': string;
    'height': number;
    'width': number;
  }
  interface ArrowIconAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'height'?: number;
    'width'?: number;
  }

  interface SvgIcon {
    'fill': string;
    'height': number;
    'viewBox': string;
    'width': number;
  }
  interface SvgIconAttributes extends StencilHTMLAttributes {
    'fill'?: string;
    'height'?: number;
    'viewBox'?: string;
    'width'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ArrowIcon': Components.ArrowIcon;
    'SvgIcon': Components.SvgIcon;
  }

  interface StencilIntrinsicElements {
    'arrow-icon': Components.ArrowIconAttributes;
    'svg-icon': Components.SvgIconAttributes;
  }


  interface HTMLArrowIconElement extends Components.ArrowIcon, HTMLStencilElement {}
  var HTMLArrowIconElement: {
    prototype: HTMLArrowIconElement;
    new (): HTMLArrowIconElement;
  };

  interface HTMLSvgIconElement extends Components.SvgIcon, HTMLStencilElement {}
  var HTMLSvgIconElement: {
    prototype: HTMLSvgIconElement;
    new (): HTMLSvgIconElement;
  };

  interface HTMLElementTagNameMap {
    'arrow-icon': HTMLArrowIconElement
    'svg-icon': HTMLSvgIconElement
  }

  interface ElementTagNameMap {
    'arrow-icon': HTMLArrowIconElement;
    'svg-icon': HTMLSvgIconElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
